name: Deployment on Heroky
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init project
        uses: actions/checkout@v2

      - name: Init Nodejs
        uses: actions/setup-node@master

      - name: Install dependances
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build page
        run: npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}